//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class analytic
    {
        public int id { get; set; }
        public Nullable<System.DateTime> publicationDate { get; set; }
        public string title { get; set; }
        public string tags { get; set; }
        public string fullContent { get; set; }
    }
}
